### ISSUE TITLE
Feature request: Some extra (pastel) colors to pick from for the website

### ISSUE THREAD

**Issue by stark-reality** [ModalSeoul/Weeb.FM#16]

**Comment by Hypsicratea** [comment]
I believe Modal said he would give users the ability to choose any colours we want for the layout.
In addition, the colour of the username text needs to be adjustable since the black text blends in with dark banners.
![untitled2](https://cloud.githubusercontent.com/assets/23017679/19654577/eba4532c-99e6-11e6-9b42-b2702229fa84.png)

**Comment by shakedown-street** [comment]
Once we upgrade the Frontend from using CSS to using SCSS I'm planning on using something like https://yeun.github.io/open-color/ as swatches for the site and adding the ability to switch themes on the settings page.  I have some seriously cool ideas that I'd like to try for theme customization.

**Comment by ModalSeoul** [comment]
This is all but complete. We're experimenting with colors and what we want to be the default primary(as you can see by visiting the site right now).

You'll be able to pick your primary & secondary colors by tonight, hopefully.

**Comment by ModalSeoul** [comment]
This is going live over the weekend.

Thanks.
